[colors]
# The default text color
foreground = "#d8dee9"
# The default background color
background = "#181818"

# Selection colors
selection_fg = "#d8dee9"
selection_bg = "#3b4252"

# Cursor colors
cursor_fg = "#181818"
cursor_bg = "#d8dee9"
cursor_border = "#d8dee9"

# ANSI black
ansi = ["#3b4252", "#bf616a", "#a3be8c", "#ebcb8b", "#5e81ac", "#b48ead", "#88c0d0", "#e5e9f0"]
# ANSI bright black
brights = ["#4c566a", "#bf616a", "#a3be8c", "#ebcb8b", "#81a1c1", "#b48ead", "#8fbcbb", "#eceff4"]

# Tab bar colors
tab_bar = {
  background = "#181818",
  active_tab = {
    bg_color = "#3b4252",
    fg_color = "#d8dee9",
    intensity = "Normal",
    underline = "None",
    italic = false,
    strikethrough = false,
  },
  inactive_tab = {
    bg_color = "#181818",
    fg_color = "#8c98a7",
  }
}
